GET http://[::1]:5000/produtos
###


POST http://[::1]:5000/produto
Content-Type: application/json

{
    "id": 5,
    "nome": "Produto 5_Test",
    "descricao": "Descrição do produto 4 teste",
    "desconto": 20.00,
    "preco": 300.0,
    "ativo": false,
    "categoria": "Teste_5_Teste",
    "data_cadastro": "2024-04-01"
}

###
GET http://[::1]:5000/produto/10
